[project]
name = "resourcecap"
version = "0.1.0"
description = "A python package to limit the resource usage of any program"
readme = "README.md"
authors = [
    { name = "purushottam-dafure", email = "purushottamdafure@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
resourcecap = "resourcecap:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
